name: Production workflow

on:
  push:
    branches:
      - main
#     paths:
#       - 'challenge-07/**'
#       - 'challenge-06/server/**'
jobs:
  build-client:
    runs-on: ubuntu-latest
    name: Deploy Client

    steps:
      - name: Development Codes
        uses: actions/checkout@v3
      - name: Use Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: 17.x
      - name: Install Dependencies
        run: yarn install
        working-directory: ./challenge-07
#       - name: Test Client
#         run: yarn run test
#         working-directory: ./challenge-07
      - name: Build Client
        run: yarn run build --if-present
        working-directory: ./challenge-07
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy --dir=build --prod
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'didapatria-challenge-client'
          heroku_email: 'didapatria3@gmail.com'
          
  build-server:
      runs-on: ubuntu-latest
      name: Deploy Server

      steps:
        - name: Development Codes
          uses: actions/checkout@v3
        - name: Use Node.js 17.x
          uses: actions/setup-node@v3
          with:
            node-version: 17.x
        - name: Install Dependencies
          run: yarn install
          working-directory: ./challenge-06/server/**
        - name: Build Server
          run: node server.js
          working-directory: ./challenge-06/server/**
        - name: Deploy to Heroku
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            args: deploy --dir=build --prod
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: 'didapatria-challenge-server'
            heroku_email: 'didapatria3@gmail.com'
